### ISSUE TITLE
TiddlyWikiInitializeTemplate pastes strange dates

### ISSUE THREAD

**Issue by sepremento** [sukima/vim-tiddlywiki#11]
Hi!

When using `:TiddlyWikiInitializeTemplate` I first get a window open with vimrun.exe and I need to navigate there and press Enter in order to get operation complete and then I see this formatting:

![tiddly_gvim](https://user-images.githubusercontent.com/28418936/84805173-4a946200-b01d-11ea-9133-af32205d95b0.png)

OS: Windows 8.1
Vim 8.2

What can I do to improve my condition?

**UPD:** Solved first part of the problem. The vimrun.exe window opened and stayed there because of the wrong (don't know why) shell. Changed from `C:\Windows\System32\cmd.exe` to `powershell` and the window does not appear, template appears smoothly.

But now the template looks like this:
![tiddly_gvim2](https://user-images.githubusercontent.com/28418936/84815213-25f3b680-b02c-11ea-978e-7be8506314f5.png)

**UPD_2:** When I invoke date insertion with `:r !date -u "+\%Y\%m\%d\%H\%M\%S"` everything is correct

**Comment by creinig** [comment]
Fascinating. My first impulse (ok, after a bit of searching) was to say that the 'date' utility required here doesn't seem to be present in a useful form under Windows. But your experiment indicates that powershell does come with a useful version. The remaining formatting problem looks like 'date' prints its result in UTF-16 and vim does not know that. The <ff><fe> at the start is actually the byte order mark for UTF-16 (little endian). We can add a filter step to remove these extra chars

**Comment by creinig** [comment]
I added a little filter - please try again with the latest version

**Comment by sepremento** [comment]
Reporting the results of my experiments:
* If I create new file with `:e foobar.tid` then explicitly `:set fenc=utf-16` and then `\tt` - the problem remains.
* If I then `:wq` and then reopen the file, the encoding somehow sets to `cp1251`
* If I reopen file with explicit `:e ++enc=utf-16` it looks like this: 
![tiddly_gvim3](https://user-images.githubusercontent.com/28418936/84889416-41a1a000-b0b2-11ea-8774-70290d73e693.png)
* If I then `:wq` and reopen, the encoding again is set to `cp1251`. It doesn't help if I `:w ++enc=utf-16`

**Comment by sepremento** [comment]
> 
> @creinig 
> I added a little filter - please try again with the latest version

**It worked! Thank you very much!**

But there was something peculiar still: I could not update my plugins via vim-plug with `:PlugUpdate` until I changed back my shell to default. I don't think it is somehow connected, but maybe you've encountered something like this before and this is trivial in general.
