### ISSUE TITLE
tiddlywiki_dir already set but still say tiddler dir could not be determined

### ISSUE THREAD

**Issue by OriLiMu** [sukima/vim-tiddlywiki#13]
neovim 0.4.4 

Already set this global variable, but still echo 

> ERROR: tiddler dir could not be determined when running Edit like command
how to fix it

Both dir setting tried but neither work
```
let g:tiddlywiki_dir = '/home/lizhe/origami_note/origami_wiki/'

let g:tiddlywiki_dir = '/home/lizhe/origami_note/origami_wiki/tiddlers/'
```

**Comment by creinig** [comment]
The plugin looks for the presence of system tiddlers (`$__*.tid`) in that dir. Do you have these in your dir?

**Comment by OriLiMu** [comment]
> The plugin looks for the presence of system tiddlers (`$__*.tid`) in that dir. Do you have these in your dir?

yes the second dir contains tid file both dir I have tried

**Comment by OriLiMu** [comment]
> The plugin looks for the presence of system tiddlers (`$__*.tid`) in that dir. Do you have these in your dir?

Both dir tried bellow, the second one contains the `tid` file. But still wont work.
> let g:tiddlywiki_dir = '/home/lizhe/origami_note/origami_wiki/'
let g:tiddlywiki_dir = '/home/lizhe/origami_note/origami_wiki/tiddlers/'

**Comment by OriLiMu** [comment]
solved Ned modify the HasSystemTiddlers function

```
 "return len(globpath(a:dir, '$__*.tid', 1, 1)) > 0 " This line dont match the $__xxx.tid file I dont know why yet
 return len(globpath(a:dir, '*.tid', 1, 1)) > 0 "This worked
```

**Comment by creinig** [comment]
Thanks for the fix, I've applied it.
I'm pretty mystified though - I just tried the original glob call manually, and it matches all tiddlers, even those without the '$__' prefix. (nvim 0.4.4 in termux)
